#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CityApp.Resource", IsApplication=true)]

namespace CityApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ModernHttpClient.Resource.String.library_name = global::CityApp.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01001f
			public const int pacv_adapterClass = 2130771999;
			
			// aapt resource value: 0x7f01001e
			public const int pacv_googleMapsApiKey = 2130771998;
			
			// aapt resource value: 0x7f010020
			public const int pacv_historyFile = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int pacv_languageCode = 2130772001;
			
			// aapt resource value: 0x7f01001d
			public const int pacv_placesAutoCompleteTextViewStyle = 2130771997;
			
			// aapt resource value: 0x7f010022
			public const int pacv_resultType = 2130772002;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04000e
			public const int common_google_signin_btn_text_dark = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int common_google_signin_btn_text_dark_default = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_google_signin_btn_text_dark_disabled = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int common_google_signin_btn_text_dark_focused = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_dark_pressed = 2130968585;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_signin_btn_text_light = 2130968591;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_signin_btn_text_light_default = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_signin_btn_text_light_disabled = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_signin_btn_text_light_focused = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_signin_btn_text_light_pressed = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int place_autocomplete_prediction_primary_text = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int place_autocomplete_prediction_primary_text_highlight = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int place_autocomplete_prediction_secondary_text = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int place_autocomplete_search_hint = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int place_autocomplete_search_text = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int place_autocomplete_separator = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int place_autocomplete_button_padding = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int place_autocomplete_powered_by_google_height = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int place_autocomplete_powered_by_google_start = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int place_autocomplete_prediction_height = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int place_autocomplete_prediction_horizontal_margin = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int place_autocomplete_prediction_primary_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int place_autocomplete_prediction_secondary_text = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int place_autocomplete_progress_horizontal_margin = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int place_autocomplete_progress_size = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int place_autocomplete_separator_start = 2131034121;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pacv_popup_background_white = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int pacv_powered_by_google_on_non_white = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int pacv_powered_by_google_on_white = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int places_ic_clear = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int places_ic_search = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int powered_by_google_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int powered_by_google_light = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000d
			public const int address = 2131296269;
			
			// aapt resource value: 0x7f090005
			public const int adjust_height = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int adjust_width = 2131296262;
			
			// aapt resource value: 0x7f09000a
			public const int auto = 2131296266;
			
			// aapt resource value: 0x7f09001d
			public const int autocomplete = 2131296285;
			
			// aapt resource value: 0x7f09000b
			public const int dark = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int establishment = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int geocode = 2131296271;
			
			// aapt resource value: 0x7f090000
			public const int hybrid = 2131296256;
			
			// aapt resource value: 0x7f090007
			public const int icon_only = 2131296263;
			
			// aapt resource value: 0x7f09000c
			public const int light = 2131296268;
			
			// aapt resource value: 0x7f09001b
			public const int name = 2131296283;
			
			// aapt resource value: 0x7f090010
			public const int no_type = 2131296272;
			
			// aapt resource value: 0x7f090001
			public const int none = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int normal = 2131296258;
			
			// aapt resource value: 0x7f09001c
			public const int number = 2131296284;
			
			// aapt resource value: 0x7f090013
			public const int place_autocomplete_clear_button = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int place_autocomplete_powered_by_google = 2131296277;
			
			// aapt resource value: 0x7f090017
			public const int place_autocomplete_prediction_primary_text = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int place_autocomplete_prediction_secondary_text = 2131296280;
			
			// aapt resource value: 0x7f090016
			public const int place_autocomplete_progress = 2131296278;
			
			// aapt resource value: 0x7f090011
			public const int place_autocomplete_search_button = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int place_autocomplete_search_input = 2131296274;
			
			// aapt resource value: 0x7f090014
			public const int place_autocomplete_separator = 2131296276;
			
			// aapt resource value: 0x7f090003
			public const int satellite = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int standard = 2131296264;
			
			// aapt resource value: 0x7f09001e
			public const int start = 2131296286;
			
			// aapt resource value: 0x7f090004
			public const int terrain = 2131296260;
			
			// aapt resource value: 0x7f090019
			public const int textView1 = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int textView2 = 2131296282;
			
			// aapt resource value: 0x7f090009
			public const int wide = 2131296265;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int pacv_maps_autocomplete_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int place_autocomplete_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int place_autocomplete_item_powered_by_google = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int place_autocomplete_item_prediction = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int place_autocomplete_progress = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int StartPage = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060016
			public const int ApplicationName = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int Hello = 2131099669;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_enable_button = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_enable_text = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_title = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_install_button = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_install_text = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_install_title = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_notification_ticker = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_unknown_issue = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_unsupported_text = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_update_button = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_update_text = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_update_title = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_updating_text = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_wear_update_text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_open_on_phone = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int common_signin_button_text = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int common_signin_button_text_long = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int library_name = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int pacv_default_history_file_name = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int place_autocomplete_clear_button = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int place_autocomplete_search_hint = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int PACV_TextAppearance_PlacesAutoComplete = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int PACV_Widget_PlacesAutoCompleteTextView = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] PlacesAutocompleteTextView = new int[] {
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002};
			
			// aapt resource value: 1
			public const int PlacesAutocompleteTextView_pacv_adapterClass = 1;
			
			// aapt resource value: 0
			public const int PlacesAutocompleteTextView_pacv_googleMapsApiKey = 0;
			
			// aapt resource value: 2
			public const int PlacesAutocompleteTextView_pacv_historyFile = 2;
			
			// aapt resource value: 3
			public const int PlacesAutocompleteTextView_pacv_languageCode = 3;
			
			// aapt resource value: 4
			public const int PlacesAutocompleteTextView_pacv_resultType = 4;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
